//
//  UserQuotesPreviewParameterProvider.swift
//  ui
//
//  Created by Damien Gironnet on 07/04/2023.
//

import Foundation
import model
import domain

///
/// Class providing UserQuotes for Preview
///
public class UserQuotesPreviewParameterProvider {
    
    public static let quotes: [UserQuote] = [
        UserQuote(quote : Quote(
            idQuote: UUID().uuidString,
            topics: [
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Omniprésence",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .theme),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "XVII",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .century),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .movement),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Astasahasrika Prajnaparamita Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .book)
            ],
            language: Locale.current.identifier,
            quote: "L'esprit est toujours vérité, vérité orientée vers l'éternel. L'esprit échappe au temps et à l'espace. Par son caractère intégral, il s'oppose au morcellement temporel et spatial. L'esprit n'est pas être, mais il est le sens de l'être, la vérité de l'être. L'esprit est également intelligence, mais une intelligence intégrale. L'esprit est aussi bien transcendant qu'immanent. En lui le transcendant devient immanent et l'immanent transcendant. L'esprit n'est pas identique à la conscience, mais la conscience se construit par l'esprit, et c'est aussi l'esprit qui transcende les limites de la conscience, qui atteint au supraconscient. L'esprit présente un aspect prométhéen, il se révolte contre les dieux de la nature, contre le déterminisme du destin humain ; l'esprit est une évasion, une évasion vers un monde supérieur et libre.")),
        UserQuote(quote: Quote(
            idQuote: UUID().uuidString,
            topics: [
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Omniprésence",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .theme),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "XVII",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .century),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .movement),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Astasahasrika Prajnaparamita Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .book)
            ],
            language: Locale.current.identifier,
            quote: "Dans son Essence, la Foi est une, quelle que soit la religion qui l'exprime. La foi est l'essence de la religion, atmosphère peuplée de trois catégories d'hommes: la masse crédule, les prédicateurs aveuglés par des luttes de clocher, enfin des initiés qui ont trouvé Dieu et l'adorent en vérité et en silence.")
        ),
        UserQuote(quote: Quote(
            idQuote: UUID().uuidString,
            topics: [
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Omniprésence",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .theme),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "XVII",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .century),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .movement),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Astasahasrika Prajnaparamita Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .book)
            ],
            language: Locale.current.identifier,
            quote: "Des imprégnations très variées issues de la tension agitée sont unies à la conscience. L'homme ordinaire les perçoit comme extérieures et ne voit pas l'essence de la conscience. L'essence de la conscience est pure, mais non la conscience provenant de l'erreur. L'erreur est faite de tension, ainsi on ne perçoit pas la Conscience.")),
        UserQuote(quote: Quote(
            idQuote: UUID().uuidString,
            topics: [
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Astasahasrika Prajnaparamita Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .book)
            ],
            language: Locale.current.identifier,
            quote: "La véritable extinction, c'est de supprimer la conscience mentale, la différenciatrice..., car pour agir, c'est sur elle que prennent appui les autres consciences... Cette conscience s'attache à la sphère sensorielle qu'elle discerne en la délimitant à l'aide des imprégnations. C'est elle aussi qui alimente la conscience de tréfonds.")),
        UserQuote(quote: Quote(
            idQuote: UUID().uuidString,
            topics: [
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Omniprésence",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .theme),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "XVII",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .century),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .movement),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Astasahasrika Prajnaparamita Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .book)
            ],
            language: Locale.current.identifier,
            quote: "Chez l'homme qui ne veille pas sur sa conduite, la soif s'étend comme une liane... Celui qui ici-bas secoue le joug très difficile à secouer de la soif, comme des gouttes d'eau roulant sur une feuille de lotus, la douleur se détache peu à peu de lui.")),
        UserQuote(quote: Quote(
            idQuote: UUID().uuidString,
            topics: [
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Omniprésence",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .theme),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "XVII",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .century),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .movement),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Astasahasrika Prajnaparamita Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .book)
            ],
            language: Locale.current.identifier,
            quote: "Chez l'homme qui ne veille pas sur sa conduite, la soif s'étend comme une liane... Celui qui ici-bas secoue le joug très difficile à secouer de la soif, comme des gouttes d'eau roulant sur une feuille de lotus, la douleur se détache peu à peu de lui.")),
        UserQuote(quote: Quote(
            idQuote: UUID().uuidString,
            topics: [
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Omniprésence",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .theme),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "XVII",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .century),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .movement),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Astasahasrika Prajnaparamita Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .book)
            ],
            language: Locale.current.identifier,
            quote: "Chez l'homme qui ne veille pas sur sa conduite, la soif s'étend comme une liane... Celui qui ici-bas secoue le joug très difficile à secouer de la soif, comme des gouttes d'eau roulant sur une feuille de lotus, la douleur se détache peu à peu de lui.")),
        UserQuote(quote: Quote(
            idQuote: UUID().uuidString,
            topics: [
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Omniprésence",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .theme),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "XVII",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .century),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .movement),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Astasahasrika Prajnaparamita Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .book)
            ],
            language: Locale.current.identifier,
            quote: "Chez l'homme qui ne veille pas sur sa conduite, la soif s'étend comme une liane... Celui qui ici-bas secoue le joug très difficile à secouer de la soif, comme des gouttes d'eau roulant sur une feuille de lotus, la douleur se détache peu à peu de lui.")),
        UserQuote(quote: Quote(
            idQuote: UUID().uuidString,
            topics: [
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Omniprésence",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .theme),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "XVII",
                      shortDescription: "",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .century),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .movement),
                Topic(id: UUID().uuidString,
                      language: Locale.current.identifier,
                      name: "Astasahasrika Prajnaparamita Theravada",
                      shortDescription: "recueil de textes sur la perfection de la sapience (-Ie au IIe siècle)",
                      longDescription: "",
                      idResource: UUID().uuidString,
                      kind: .book)
            ],
            language: Locale.current.identifier,
            quote: "Chez l'homme qui ne veille pas sur sa conduite, la soif s'étend comme une liane... Celui qui ici-bas secoue le joug très difficile à secouer de la soif, comme des gouttes d'eau roulant sur une feuille de lotus, la douleur se détache peu à peu de lui."))
    ]
}
